#include <limits.h>
#include <string.h>

#include "demos/recog/recog.h"

/* Built-in template pool, generated by gen_templates.py. */
extern const uint8_t recog_pool[];
extern const unsigned int recog_pool_len;
extern const unsigned int recog_builtin_count;

#define FP_SHIFT   5   /* working coordinates are dots << 5 */
#define MAX_IN     512 /* most input points taken */
#define MAX_TMPL_PTS 320
#define BUILTIN_MAX 96
#define MIN_EXTENT_DOTS 6 /* smaller drawings are taps, not characters */
#define START_STEP  5     /* floor(sqrt(RECOG_N)), the $P start-point step */

struct wpt {
	int32_t x;
	int32_t y;
	uint8_t id;
};

/* Reused scratch, so recognition is not reentrant (single UI thread). */
static struct wpt work[MAX_IN];

static struct recog_cloud builtin[BUILTIN_MAX];
static char builtin_ch[BUILTIN_MAX];
static uint8_t builtin_kind[BUILTIN_MAX];
static int builtin_n;
static int built;

static struct {
	char ch;
	struct recog_cloud c;
} user[RECOG_MAX_USER];
static int user_n;
static int user_head;

static uint32_t isqrt32(uint32_t v)
{
	uint32_t r = 0;
	uint32_t b = 1u << 30;

	while (b > v) {
		b >>= 2;
	}
	while (b) {
		if (v >= r + b) {
			v -= r + b;
			r = (r >> 1) + b;
		} else {
			r >>= 1;
		}
		b >>= 2;
	}
	return r;
}

static int32_t dist32(int32_t x0, int32_t y0, int32_t x1, int32_t y1)
{
	int32_t dx = x1 - x0;
	int32_t dy = y1 - y0;

	return (int32_t)isqrt32((uint32_t)(dx * dx + dy * dy));
}

/* Resample the polyline(s) in p[0..n) to RECOG_N points, equally spaced along
 * the path; the gap between two strokes counts as zero length. */
static int resample(const struct wpt *p, int n, int32_t *ox, int32_t *oy)
{
	int32_t len = 0;

	for (int i = 1; i < n; i++) {
		if (p[i].id == p[i - 1].id) {
			len += dist32(p[i - 1].x, p[i - 1].y, p[i].x, p[i].y);
		}
	}

	int32_t step = len / (RECOG_N - 1);

	if (step < 1) {
		return -1;
	}

	int cnt = 1;
	int32_t acc = 0;
	int32_t px = p[0].x;
	int32_t py = p[0].y;

	ox[0] = px;
	oy[0] = py;

	for (int i = 1; i < n && cnt < RECOG_N; i++) {
		if (p[i].id != p[i - 1].id) {
			px = p[i].x;
			py = p[i].y;
			continue;
		}

		int32_t cx = p[i].x;
		int32_t cy = p[i].y;

		for (;;) {
			int32_t d = dist32(px, py, cx, cy);

			if (d > 0 && acc + d >= step) {
				int32_t t = step - acc;
				int32_t qx = px + (int32_t)((int64_t)t * (cx - px) / d);
				int32_t qy = py + (int32_t)((int64_t)t * (cy - py) / d);

				ox[cnt] = qx;
				oy[cnt] = qy;
				cnt++;
				px = qx;
				py = qy;
				acc = 0;
				if (cnt >= RECOG_N) {
					break;
				}
			} else {
				acc += d;
				px = cx;
				py = cy;
				break;
			}
		}
	}

	while (cnt < RECOG_N) { /* rounding left the last point(s) out */
		ox[cnt] = p[n - 1].x;
		oy[cnt] = p[n - 1].y;
		cnt++;
	}
	return 0;
}

/* Scale to a unit box (longer side = 1000) and centre on the centroid. */
static void to_cloud(const int32_t *x, const int32_t *y, struct recog_cloud *out)
{
	int32_t minx = x[0], maxx = x[0], miny = y[0], maxy = y[0];

	for (int i = 1; i < RECOG_N; i++) {
		if (x[i] < minx) {
			minx = x[i];
		}
		if (x[i] > maxx) {
			maxx = x[i];
		}
		if (y[i] < miny) {
			miny = y[i];
		}
		if (y[i] > maxy) {
			maxy = y[i];
		}
	}

	int32_t scale = (maxx - minx) > (maxy - miny) ? (maxx - minx) : (maxy - miny);

	if (scale < 1) {
		scale = 1;
	}

	int32_t nx[RECOG_N], ny[RECOG_N];
	int32_t sx = 0, sy = 0;

	for (int i = 0; i < RECOG_N; i++) {
		nx[i] = (int32_t)((int64_t)(x[i] - minx) * 1000 / scale);
		ny[i] = (int32_t)((int64_t)(y[i] - miny) * 1000 / scale);
		sx += nx[i];
		sy += ny[i];
	}
	sx /= RECOG_N;
	sy /= RECOG_N;
	for (int i = 0; i < RECOG_N; i++) {
		out->x[i] = (int16_t)(nx[i] - sx);
		out->y[i] = (int16_t)(ny[i] - sy);
	}
}

int recog_normalize(const struct recog_pt *pts, int n, struct recog_cloud *out)
{
	if (n < 2) {
		return -1;
	}
	if (n > MAX_IN) {
		n = MAX_IN;
	}

	int minx = pts[0].x, maxx = pts[0].x, miny = pts[0].y, maxy = pts[0].y;

	for (int i = 0; i < n; i++) {
		work[i].x = (int32_t)pts[i].x << FP_SHIFT;
		work[i].y = (int32_t)pts[i].y << FP_SHIFT;
		work[i].id = pts[i].id;
		if (pts[i].x < minx) {
			minx = pts[i].x;
		}
		if (pts[i].x > maxx) {
			maxx = pts[i].x;
		}
		if (pts[i].y < miny) {
			miny = pts[i].y;
		}
		if (pts[i].y > maxy) {
			maxy = pts[i].y;
		}
	}
	if ((maxx - minx) < MIN_EXTENT_DOTS && (maxy - miny) < MIN_EXTENT_DOTS) {
		return -1;
	}

	int32_t x[RECOG_N], y[RECOG_N];

	if (resample(work, n, x, y) != 0) {
		return -1;
	}
	to_cloud(x, y, out);
	return 0;
}

static void build_builtin(void)
{
	unsigned int pos = 0;
	static struct wpt tp[MAX_TMPL_PTS];

	built = 1;
	builtin_n = 0;
	while (pos < recog_pool_len && builtin_n < BUILTIN_MAX) {
		char ch = (char)recog_pool[pos++];
		uint8_t kind = recog_pool[pos++];
		uint8_t ns = recog_pool[pos++];
		int np = 0;

		for (uint8_t s = 0; s < ns; s++) {
			uint8_t cnt = recog_pool[pos++];

			for (uint8_t k = 0; k < cnt; k++) {
				int32_t x = recog_pool[pos++];
				int32_t y = recog_pool[pos++];

				if (np < MAX_TMPL_PTS) {
					tp[np].x = x << FP_SHIFT;
					tp[np].y = y << FP_SHIFT;
					tp[np].id = s;
					np++;
				}
			}
		}

		int32_t rx[RECOG_N], ry[RECOG_N];

		if (np >= 2 && resample(tp, np, rx, ry) == 0) {
			to_cloud(rx, ry, &builtin[builtin_n]);
			builtin_ch[builtin_n] = ch;
			builtin_kind[builtin_n] = kind;
			builtin_n++;
		}
	}
}

/* Greedy weighted nearest-point matching a -> b starting at point `start`.
 * Returns the weighted sum of distances, or early with a value >= limit. */
static uint32_t cloud_dist(const struct recog_cloud *a, const struct recog_cloud *b, int start,
			   uint32_t limit)
{
	uint8_t matched[RECOG_N];
	uint32_t sum = 0;
	int i = start;

	memset(matched, 0, sizeof(matched));
	for (int k = 0; k < RECOG_N; k++) {
		int best = -1;
		uint32_t best_sq = UINT32_MAX;

		for (int j = 0; j < RECOG_N; j++) {
			if (matched[j]) {
				continue;
			}

			int32_t dx = a->x[i] - b->x[j];
			int32_t dy = a->y[i] - b->y[j];
			uint32_t sq = (uint32_t)(dx * dx + dy * dy);

			if (sq < best_sq) {
				best_sq = sq;
				best = j;
			}
		}
		matched[best] = 1;
		sum += (uint32_t)(RECOG_N - k) * isqrt32(best_sq);
		if (sum >= limit) {
			return sum;
		}
		i = (i + 1) % RECOG_N;
	}
	return sum;
}

static uint32_t cloud_match(const struct recog_cloud *a, const struct recog_cloud *b,
			    uint32_t limit)
{
	uint32_t best = limit;

	for (int start = 0; start < RECOG_N; start += START_STEP) {
		uint32_t d = cloud_dist(a, b, start, best);

		if (d < best) {
			best = d;
		}
		d = cloud_dist(b, a, start, best);
		if (d < best) {
			best = d;
		}
	}
	return best;
}

static int is_digit_char(char ch)
{
	return ch >= '0' && ch <= '9';
}

int recog_classify(const struct recog_cloud *c, unsigned int mode, struct recog_cand *out, int max)
{
	char chars[40];
	uint32_t dist[40]; /* weighted sums; /RECOG_N gives the reported distance */
	int nch = 0;

	if (!built) {
		build_builtin();
	}

	for (int t = 0; t < builtin_n + user_n; t++) {
		const struct recog_cloud *tc;
		char ch;
		int digit;

		if (t < builtin_n) {
			tc = &builtin[t];
			ch = builtin_ch[t];
			digit = builtin_kind[t] == 'D';
		} else {
			tc = &user[t - builtin_n].c;
			ch = user[t - builtin_n].ch;
			digit = is_digit_char(ch);
		}
		if (!(mode & (digit ? RECOG_DIGITS : RECOG_LETTERS))) {
			continue;
		}

		int slot = -1;

		for (int k = 0; k < nch; k++) {
			if (chars[k] == ch) {
				slot = k;
				break;
			}
		}

		uint32_t limit = slot >= 0 ? dist[slot] : UINT32_MAX;
		uint32_t d = cloud_match(c, tc, limit);

		if (slot < 0) {
			if (nch < (int)(sizeof(chars))) {
				chars[nch] = ch;
				dist[nch] = d;
				nch++;
			}
		} else if (d < dist[slot]) {
			dist[slot] = d;
		}
	}

	int n = 0;

	while (n < max && n < nch) { /* selection sort: smallest first */
		int bi = n;

		for (int k = n + 1; k < nch; k++) {
			if (dist[k] < dist[bi]) {
				bi = k;
			}
		}
		if (bi != n) {
			char tc = chars[n];
			uint32_t td = dist[n];

			chars[n] = chars[bi];
			dist[n] = dist[bi];
			chars[bi] = tc;
			dist[bi] = td;
		}

		uint32_t d = dist[n] / RECOG_N;
		int conf = (1600 - (int)d) / 12;

		out[n].ch = chars[n];
		out[n].dist = d > 65535 ? 65535 : (uint16_t)d;
		out[n].conf = conf < 0 ? 0 : (conf > 100 ? 100 : (uint8_t)conf);
		n++;
	}
	return n;
}

int recog_teach(char ch, const struct recog_cloud *c)
{
	user[user_head].ch = ch;
	user[user_head].c = *c;
	user_head = (user_head + 1) % RECOG_MAX_USER;
	if (user_n < RECOG_MAX_USER) {
		user_n++;
	}
	return user_n;
}

int recog_user_count(void)
{
	return user_n;
}

void recog_user_clear(void)
{
	user_n = 0;
	user_head = 0;
}
